# Generated by Django 4.1 on 2022-09-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_title',
            field=models.CharField(default='roberts', max_length=255),
        ),
    ]
